### ISSUE TITLE
Problem on reservation

### ISSUE THREAD

**Issue by Saroj058** [anushaneupane966/HotelBooking#112]
View reservation should show the future reservation and history reservation should show the past reservation but they both are showing the same fix it.

**Comment by Stha-Parichit** [comment]
![image](https://github.com/anushaneupane966/HotelBooking/assets/119142592/a60bf07c-583f-48b4-8411-cd1589d1ec6a)
![image](https://github.com/anushaneupane966/HotelBooking/assets/119142592/8c41c598-9856-4cc7-9090-cfbe85b387e0)
here is the proof of the issued solved
