### ISSUE TITLE
Login wrong credentials redirect bug

### ISSUE THREAD

**Issue by manuahree** [anushaneupane966/HotelBooking#19]
When the user login with wrong credentials the website is redirected to login.php showing just invalid message. Please fix it

**Comment by Stha-Parichit** [comment]
![WrongCredentialsBug](https://github.com/anushaneupane966/HotelBooking/assets/119142592/4dbb324c-f4c6-4016-af03-07ba920321a5)
I have already fixed that bug please review it

**Comment by Stha-Parichit** [comment]
I have also handled the form submission error(if the form is not submitted the site is redirected to login page)

**Comment by manuahree** [comment]
I reviewed your work, and everything is fine.

**Comment by manuahree** [comment]
I reviewed your work, and everything is fine.
