### ISSUE TITLE
Fix bug of navigation to login page after sign in 

### ISSUE THREAD

**Issue by manuahree** [anushaneupane966/HotelBooking#20]
Users get stuck in a login loop, being sent back to the login page after successfully signing in. Please fix it

**Comment by Chalisebinod** [comment]
Issue has been solved
![image](https://github.com/anushaneupane966/HotelBooking/assets/119122052/51a21c97-c4d0-484a-90f0-f2bc00bfacf1)

**Comment by Chalisebinod** [comment]
Issue close Garey maile ....vayo tw?
