### ISSUE TITLE
Issue on booking page 

### ISSUE THREAD

**Issue by manuahree** [anushaneupane966/HotelBooking#88]
When booking, the number of guests should be one or more, but in our system, the number of guests can be negative. 
please fix this problem

**Comment by Stha-Parichit** [comment]
![image](https://github.com/anushaneupane966/HotelBooking/assets/119142592/0fa0670c-f66b-4459-aed8-55595ab8fd66)

**Comment by Stha-Parichit** [comment]
I have solved the issue
