### ISSUE TITLE
Issue on Signup 

### ISSUE THREAD

**Issue by manuahree** [anushaneupane966/HotelBooking#93]
During the sign-up process, the same email address is used multiple times. Which shouldn't be. fix that issue as fast as possible

**Comment by sanju-maskey-shrestha** [comment]
![Screenshot 2024-05-19 133246](https://github.com/anushaneupane966/HotelBooking/assets/121472889/f4fff7bb-5015-4637-bf67-9f63555d4b77)

**Comment by sanju-maskey-shrestha** [comment]
I have solved the issue here is the proof
